INSERT INTO tb_book_list (name) VALUES ('Livros físicos');
INSERT INTO tb_book_list (name) VALUES ('Livros Kindle');


INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('Pessoas Altamente Sensíveis', 100.0, 2021, 'Autoconhecimento, Autoajuda', 'Livro físico', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHgH8xA_6R0p3VK_o8i_MaPkrfkbvK2JmHLw&s', 'Fonte da imagem: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHgH8xA_6R0p3VK_o8i_MaPkrfkbvK2JmHLw&s', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('A arte da Guerrra', 4.7, 2011, 'Estratégia, Autodesenvolvimento', 'Livro', 'https://cdn.record.com.br/wp-content/uploads/2020/08/25160528/14766.jpeg', ' Fonte da imagem: https://cdn.record.com.br/wp-content/uploads/2020/08/25160528/14766.jpeg ', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('O livro dos Códigos', 2.5, 2023, 'Criptografia, História', 'Livro Físico', 'https://images-americanas.b2w.io/produtos/187421/imagens/livro-o-livro-dos-codigos/187421_1_large.jpg', 'Fonte da imagem: https://images-americanas.b2w.io/produtos/187421/imagens/livro-o-livro-dos-codigos/187421_1_large.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('As Crônicas de Nárnia, O leão, a feiticeira e o guarda-roupas', 100.0, 2009, 'Aventura, fantasia, ficção', 'Kindle', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDBRkGItcmLC0BdieOu04hd_Pi8OF9ubtCmg&s', ' Fonte da imagem: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDBRkGItcmLC0BdieOu04hd_Pi8OF9ubtCmg&s ', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('As Crônicas de Narnia, O cavalo e seu Menino' 5.2, 2023, 'Aventura, fantasia, ficção', 'Kindle', 'https://m.media-amazon.com/images/I/71aPtIezcWL._AC_UF1000,1000_QL80_.jpg', ' Fonte da imagem: https://m.media-amazon.com/images/I/71aPtIezcWL._AC_UF1000,1000_QL80_.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('Apaixone-se por si mesmo', 100.0, 2012, 'Autoajuda', 'kindle', 'https://m.media-amazon.com/images/I/71tPdMqvqfL._SY425_.jpg', ' Fonte da imagem: https://m.media-amazon.com/images/I/71tPdMqvqfL._SY425_.jpg ', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('Café com autoestima', 3.5, 2022, 'Autoajuda', 'Kindle', 'https://m.media-amazon.com/images/I/71XBxX2zkQL._AC_UF1000,1000_QL80_.jpg', 'Fonte da imagem: https://m.media-amazon.com/images/I/71XBxX2zkQL._AC_UF1000,1000_QL80_.jpg ', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('O ego é seu pior inimigo', 100.0, 2017, 'autoajuda', 'Kindle', 'https://m.media-amazon.com/images/I/61wr4eRbOUL._AC_UF1000,1000_QL80_.jpg', ' Fonte da imagem: https://m.media-amazon.com/images/I/61wr4eRbOUL._AC_UF1000,1000_QL80_.jpg ', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('A física e o mundo que nos rodeia', 2.2, 1994, 'Física', 'Livro Físico','https://m.media-amazon.com/images/I/41Er5NGxLVS._SY445_SX342_.jpg', 'Fonte da imagem: https://m.media-amazon.com/images/I/41Er5NGxLVS._SY445_SX342_.jpg ', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_book (title, score, book_year, genre, platforms, img_url, short_description, long_description) VALUES ('A Coragem de Ser Imperfeito', 1.5, 2016, 'autoajuda', 'Kindle', 'https://m.media-amazon.com/images/I/41Er5NGxLVS._SY445_SX342_.jpg', 'Fonte da imagem: https://m.media-amazon.com/images/I/41Er5NGxLVS._SY445_SX342_.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');

INSERT INTO tb_belonging (list_id, book_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (1, 9, 3);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 4, 4);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 5, 0);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 6, 1);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 7, 2);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 8, 3);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 10, 4);